// <auto-generated />
using System;
using IHostPro.Contexts.Dashboard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IHostPro.Contexts.Dashboard.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    [Migration("20260817173347_AddCancelledAtUtcToProjections")]
    partial class AddCancelledAtUtcToProjections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dashboard")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IHostPro.Contexts.Dashboard.Infrastructure.Projections.DashboardCleaningProjectionEntry", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("CleaningId")
                        .HasColumnType("uuid")
                        .HasColumnName("cleaning_id");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid?>("HousekeeperUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("housekeeper_user_id");

                    b.Property<DateTimeOffset>("LastEventAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at_utc");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset?>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at_utc");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("TenantId", "CleaningId");

                    b.HasIndex("TenantId", "CancelledAtUtc");

                    b.HasIndex("TenantId", "CompletedAtUtc");

                    b.HasIndex("TenantId", "PropertyId");

                    b.HasIndex("TenantId", "ScheduledAtUtc");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("cleaning_projection", "dashboard");
                });

            modelBuilder.Entity("IHostPro.Contexts.Dashboard.Infrastructure.Projections.DashboardOccurrenceProjectionEntry", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("occurrence_id");

                    b.Property<Guid>("CleaningId")
                        .HasColumnType("uuid")
                        .HasColumnName("cleaning_id");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("TenantId", "OccurrenceId");

                    b.HasIndex("TenantId", "CleaningId");

                    b.HasIndex("TenantId", "RegisteredAtUtc");

                    b.HasIndex("TenantId", "Type");

                    b.ToTable("occurrence_projection", "dashboard");
                });

            modelBuilder.Entity("IHostPro.Contexts.Dashboard.Infrastructure.Projections.DashboardPropertyProjectionEntry", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("LastEventAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("TenantId", "PropertyId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("property_projection", "dashboard");
                });

            modelBuilder.Entity("IHostPro.Contexts.Dashboard.Infrastructure.Projections.DashboardReservationProjectionEntry", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset?>("CheckInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_at");

                    b.Property<DateTimeOffset?>("CheckOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_at");

                    b.Property<DateTimeOffset>("LastEventAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at_utc");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("TenantId", "ReservationId");

                    b.HasIndex("TenantId", "CancelledAtUtc");

                    b.HasIndex("TenantId", "CheckInAt");

                    b.HasIndex("TenantId", "CheckOutAt");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("reservation_projection", "dashboard");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("wolverine_incoming_envelopes", "dashboard_messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("wolverine_outgoing_envelopes", "dashboard_messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
