// <auto-generated />
using System;
using IHostPro.Contexts.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IHostPro.Contexts.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource");

                    b.Property<string>("Scope")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.ToTable("permissions", "identity");

                    b.HasData(
                        new
                        {
                            Id = "PROPERTIES:MANAGE",
                            Action = "MANAGE",
                            Resource = "PROPERTIES"
                        },
                        new
                        {
                            Id = "PROPERTIES:READ",
                            Action = "READ",
                            Resource = "PROPERTIES"
                        },
                        new
                        {
                            Id = "PROPERTIES:READ:OWN_OWNER",
                            Action = "READ",
                            Resource = "PROPERTIES",
                            Scope = "OWN_OWNER"
                        },
                        new
                        {
                            Id = "RESERVATIONS:MANAGE",
                            Action = "MANAGE",
                            Resource = "RESERVATIONS"
                        },
                        new
                        {
                            Id = "RESERVATIONS:READ",
                            Action = "READ",
                            Resource = "RESERVATIONS"
                        },
                        new
                        {
                            Id = "RESERVATIONS:READ:OWN_OWNER",
                            Action = "READ",
                            Resource = "RESERVATIONS",
                            Scope = "OWN_OWNER"
                        },
                        new
                        {
                            Id = "SCHEDULE:MANAGE",
                            Action = "MANAGE",
                            Resource = "SCHEDULE"
                        },
                        new
                        {
                            Id = "SCHEDULE:READ",
                            Action = "READ",
                            Resource = "SCHEDULE"
                        },
                        new
                        {
                            Id = "SCHEDULE:READ:OWN_OWNER",
                            Action = "READ",
                            Resource = "SCHEDULE",
                            Scope = "OWN_OWNER"
                        },
                        new
                        {
                            Id = "CLEANINGS:MANAGE",
                            Action = "MANAGE",
                            Resource = "CLEANINGS"
                        },
                        new
                        {
                            Id = "CLEANINGS:MANAGE:OWN_CLEANING",
                            Action = "MANAGE",
                            Resource = "CLEANINGS",
                            Scope = "OWN_CLEANING"
                        },
                        new
                        {
                            Id = "CLEANINGS:READ",
                            Action = "READ",
                            Resource = "CLEANINGS"
                        },
                        new
                        {
                            Id = "CLEANINGS:READ:OWN_OWNER",
                            Action = "READ",
                            Resource = "CLEANINGS",
                            Scope = "OWN_OWNER"
                        },
                        new
                        {
                            Id = "POLICIES:MANAGE",
                            Action = "MANAGE",
                            Resource = "POLICIES"
                        },
                        new
                        {
                            Id = "POLICIES:READ",
                            Action = "READ",
                            Resource = "POLICIES"
                        },
                        new
                        {
                            Id = "TEMPLATES:MANAGE",
                            Action = "MANAGE",
                            Resource = "TEMPLATES"
                        },
                        new
                        {
                            Id = "TEMPLATES:READ",
                            Action = "READ",
                            Resource = "TEMPLATES"
                        },
                        new
                        {
                            Id = "SETTINGS:MANAGE",
                            Action = "MANAGE",
                            Resource = "SETTINGS"
                        },
                        new
                        {
                            Id = "SETTINGS:READ",
                            Action = "READ",
                            Resource = "SETTINGS"
                        },
                        new
                        {
                            Id = "AUDIT:READ",
                            Action = "READ",
                            Resource = "AUDIT"
                        },
                        new
                        {
                            Id = "AUDIT:USE",
                            Action = "USE",
                            Resource = "AUDIT"
                        },
                        new
                        {
                            Id = "DASHBOARD:MANAGE",
                            Action = "MANAGE",
                            Resource = "DASHBOARD"
                        },
                        new
                        {
                            Id = "DASHBOARD:READ",
                            Action = "READ",
                            Resource = "DASHBOARD"
                        },
                        new
                        {
                            Id = "DASHBOARD:READ:OWN_OWNER",
                            Action = "READ",
                            Resource = "DASHBOARD",
                            Scope = "OWN_OWNER"
                        },
                        new
                        {
                            Id = "DASHBOARD:USE",
                            Action = "USE",
                            Resource = "DASHBOARD"
                        },
                        new
                        {
                            Id = "REPORTS:MANAGE",
                            Action = "MANAGE",
                            Resource = "REPORTS"
                        },
                        new
                        {
                            Id = "REPORTS:READ",
                            Action = "READ",
                            Resource = "REPORTS"
                        },
                        new
                        {
                            Id = "REPORTS:READ:OWN_OWNER",
                            Action = "READ",
                            Resource = "REPORTS",
                            Scope = "OWN_OWNER"
                        },
                        new
                        {
                            Id = "REPORTS:USE",
                            Action = "USE",
                            Resource = "REPORTS"
                        },
                        new
                        {
                            Id = "USERS:MANAGE",
                            Action = "MANAGE",
                            Resource = "USERS"
                        },
                        new
                        {
                            Id = "ROLES:READ",
                            Action = "READ",
                            Resource = "ROLES"
                        },
                        new
                        {
                            Id = "PERMISSIONS:READ",
                            Action = "READ",
                            Resource = "PERMISSIONS"
                        });
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid?>("PreviousTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_token_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<int?>("RevocationReason")
                        .HasColumnType("integer")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TokenId")
                        .IsUnique();

                    b.HasIndex("TenantId", "UserId");

                    b.HasIndex("TenantId", "SessionId", "UserId");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.ToTable("roles", "identity");

                    b.HasData(
                        new
                        {
                            Id = "ADMIN",
                            DisplayName = "Administrador"
                        },
                        new
                        {
                            Id = "OPERATOR",
                            DisplayName = "Operador"
                        },
                        new
                        {
                            Id = "HOUSEKEEPER",
                            DisplayName = "Faxineira"
                        },
                        new
                        {
                            Id = "PROPERTY_OWNER",
                            DisplayName = "Proprietário"
                        },
                        new
                        {
                            Id = "SYSTEM",
                            DisplayName = "Sistema"
                        },
                        new
                        {
                            Id = "AI_AGENT",
                            DisplayName = "Agente IA"
                        },
                        new
                        {
                            Id = "INTEGRATION",
                            DisplayName = "Integração"
                        });
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.RolePermission", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role_code");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_code");

                    b.HasKey("RoleCode", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("role_permissions", "identity");

                    b.HasData(
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "PROPERTIES:MANAGE"
                        },
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "RESERVATIONS:MANAGE"
                        },
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "SCHEDULE:MANAGE"
                        },
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "CLEANINGS:MANAGE"
                        },
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "POLICIES:MANAGE"
                        },
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "TEMPLATES:MANAGE"
                        },
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "SETTINGS:MANAGE"
                        },
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "AUDIT:READ"
                        },
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "DASHBOARD:MANAGE"
                        },
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "REPORTS:MANAGE"
                        },
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "USERS:MANAGE"
                        },
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "ROLES:READ"
                        },
                        new
                        {
                            RoleCode = "ADMIN",
                            PermissionCode = "PERMISSIONS:READ"
                        },
                        new
                        {
                            RoleCode = "OPERATOR",
                            PermissionCode = "PROPERTIES:READ"
                        },
                        new
                        {
                            RoleCode = "OPERATOR",
                            PermissionCode = "RESERVATIONS:MANAGE"
                        },
                        new
                        {
                            RoleCode = "OPERATOR",
                            PermissionCode = "SCHEDULE:MANAGE"
                        },
                        new
                        {
                            RoleCode = "OPERATOR",
                            PermissionCode = "CLEANINGS:MANAGE"
                        },
                        new
                        {
                            RoleCode = "OPERATOR",
                            PermissionCode = "AUDIT:READ"
                        },
                        new
                        {
                            RoleCode = "OPERATOR",
                            PermissionCode = "DASHBOARD:READ"
                        },
                        new
                        {
                            RoleCode = "OPERATOR",
                            PermissionCode = "REPORTS:READ"
                        },
                        new
                        {
                            RoleCode = "HOUSEKEEPER",
                            PermissionCode = "PROPERTIES:READ"
                        },
                        new
                        {
                            RoleCode = "HOUSEKEEPER",
                            PermissionCode = "SCHEDULE:READ"
                        },
                        new
                        {
                            RoleCode = "HOUSEKEEPER",
                            PermissionCode = "CLEANINGS:MANAGE:OWN_CLEANING"
                        },
                        new
                        {
                            RoleCode = "PROPERTY_OWNER",
                            PermissionCode = "PROPERTIES:READ:OWN_OWNER"
                        },
                        new
                        {
                            RoleCode = "PROPERTY_OWNER",
                            PermissionCode = "RESERVATIONS:READ:OWN_OWNER"
                        },
                        new
                        {
                            RoleCode = "PROPERTY_OWNER",
                            PermissionCode = "SCHEDULE:READ:OWN_OWNER"
                        },
                        new
                        {
                            RoleCode = "PROPERTY_OWNER",
                            PermissionCode = "CLEANINGS:READ:OWN_OWNER"
                        },
                        new
                        {
                            RoleCode = "PROPERTY_OWNER",
                            PermissionCode = "DASHBOARD:READ:OWN_OWNER"
                        },
                        new
                        {
                            RoleCode = "PROPERTY_OWNER",
                            PermissionCode = "REPORTS:READ:OWN_OWNER"
                        },
                        new
                        {
                            RoleCode = "AI_AGENT",
                            PermissionCode = "PROPERTIES:READ"
                        },
                        new
                        {
                            RoleCode = "AI_AGENT",
                            PermissionCode = "RESERVATIONS:READ"
                        },
                        new
                        {
                            RoleCode = "AI_AGENT",
                            PermissionCode = "SCHEDULE:READ"
                        },
                        new
                        {
                            RoleCode = "AI_AGENT",
                            PermissionCode = "CLEANINGS:READ"
                        },
                        new
                        {
                            RoleCode = "AI_AGENT",
                            PermissionCode = "POLICIES:READ"
                        },
                        new
                        {
                            RoleCode = "AI_AGENT",
                            PermissionCode = "TEMPLATES:READ"
                        },
                        new
                        {
                            RoleCode = "AI_AGENT",
                            PermissionCode = "SETTINGS:READ"
                        },
                        new
                        {
                            RoleCode = "AI_AGENT",
                            PermissionCode = "AUDIT:USE"
                        },
                        new
                        {
                            RoleCode = "AI_AGENT",
                            PermissionCode = "DASHBOARD:USE"
                        },
                        new
                        {
                            RoleCode = "AI_AGENT",
                            PermissionCode = "REPORTS:USE"
                        });
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.SecurityAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code");

                    b.Property<Guid?>("RefreshTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token_id");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.HasIndex("TenantId", "SessionId", "OccurredAt");

                    b.HasIndex("TenantId", "UserId", "OccurredAt");

                    b.ToTable("security_audit_log", "identity");
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApproximateLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("approximate_location");

                    b.Property<string>("Browser")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("browser");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("sessions", "identity");
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", "identity");
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("FailedAccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_access_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role_code");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("UserId", "RoleCode");

                    b.HasIndex("RoleCode");

                    b.HasIndex("TenantId", "AssignedByUserId");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.RefreshToken", b =>
                {
                    b.HasOne("IHostPro.Contexts.Identity.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SessionId", "UserId")
                        .HasPrincipalKey("TenantId", "Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.RolePermission", b =>
                {
                    b.HasOne("IHostPro.Contexts.Identity.Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IHostPro.Contexts.Identity.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.SecurityAuditEntry", b =>
                {
                    b.HasOne("IHostPro.Contexts.Identity.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.Session", b =>
                {
                    b.HasOne("IHostPro.Contexts.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.User", b =>
                {
                    b.HasOne("IHostPro.Contexts.Identity.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IHostPro.Contexts.Identity.Domain.UserRole", b =>
                {
                    b.HasOne("IHostPro.Contexts.Identity.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IHostPro.Contexts.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssignedByUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IHostPro.Contexts.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
